language: generic

sudo: required

services:
    - docker

before_script:
    - make pull-from pull build

script:
    - make test

after_success:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - make push
