language: generic

sudo: required

services:
    - docker

env:
    matrix:
        - DISTRO=tomcat VERSION=7.6.0
        - DISTRO=tomcat VERSION=7.7.0
        - DISTRO=tomcat VERSION=7.8.0-SNAPSHOT
        - DISTRO=wildfly VERSION=7.6.0
        - DISTRO=wildfly VERSION=7.7.0
        - DISTRO=wildfly VERSION=7.8.0-SNAPSHOT

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
    - docker build -t menski/camunda-single-file:${DISTRO}-${VERSION} --build-arg DISTRO=${DISTRO} --build-arg VERSION=${VERSION} .
